# Checkov Configuration for Bedrock AgentCore Terraform
# https://www.checkov.io/

# Framework to scan
framework:
  - terraform

# Directories to scan
directory:
  - .

# Skip specific directories
skip-path:
  - .terraform
  - .git
  - node_modules
  - examples  # Example stacks are intentionally minimal
  - examples/3-deepresearch/agent-code  # Python code, not Terraform

# Output format
output:
  - cli
  - junitxml

# Compact output
compact: true

# Soft fail (don't exit non-zero) - set to false for CI
soft-fail: false

# Check IDs to skip (with justification)
skip-check:
  # Design Decisions & Architectural Patterns
  - CKV_AWS_144  # S3 cross-region replication (ADR-0007)
  - CKV_AWS_145  # S3 KMS encryption (Using SSE-S3 ADR-0008)
  - CKV_AWS_19   # S3 Encryption (Using SSE-S3 ADR-0008)
  - CKV_AWS_158  # CloudWatch KMS (Using AWS-managed encryption ADR-0008)
  - CKV_AWS_338  # Log retention >= 1 year
  - CKV_AWS_18   # S3 access logging (Skipped for non-critical buckets)
  - CKV_AWS_21   # S3 versioning (False positives)
  - CKV2_AWS_6   # S3 public access block (Enforced via separate resources)
  - CKV2_AWS_62  # S3 event notifications
  - CKV2_AWS_61  # S3 lifecycle configuration (Managed manually)
  - CKV2_AWS_34  # Non-secret SSM String parameters are used for identifiers (e.g., inference profile ARN), not secrets

  # Serverless & Lambda Specifics
  - CKV_AWS_115  # Lambda concurrency
  - CKV_AWS_116  # Lambda DLQ
  - CKV_AWS_117  # Lambda VPC (Public reachability required for OIDC/Bedrock)
  - CKV_AWS_173  # IAM full access (False positives on Bedrock)
  - CKV_AWS_107  # IAM policy should not allow * action (Required for some Bedrock ops)
  - CKV_AWS_108  # IAM policy should not allow * resource (Bedrock requirement)
  - CKV_AWS_109  # IAM policy should not allow * resource (Bedrock requirement)
  - CKV_AWS_110  # IAM policy should not allow * resource (Bedrock requirement)
  - CKV_AWS_111  # IAM wildcard requirement (Documented AWS exceptions)
  - CKV_AWS_356  # IAM full access (Cross-account assumption requirement)

# Download external modules for scanning
download-external-modules: false

# Evaluate variables
evaluate-variables: true

# Enable secrets scanning
enable-secret-scan-all-files: true

# Block list for secrets (patterns to flag)
block-list-secret-scan:
  - "aws_access_key_id"
  - "aws_secret_access_key"
  - "password"
  - "secret"
  - "token"
  - "api_key"

# Summary position
summary-position: bottom
