name: Terraform Setup
description: Setup Terraform with plugin caching
inputs:
  terraform_version:
    description: Terraform version to install
    required: false
    default: "1.14.4"
runs:
  using: composite
  steps:
    - name: Set Terraform plugin cache env
      shell: bash
      run: |
        echo "TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache" >> "$GITHUB_ENV"
    - name: Cache Terraform plugins
      uses: actions/cache@v4
      with:
        path: ~/.terraform.d/plugin-cache
        key: ${{ runner.os }}-terraform-plugins-${{ hashFiles('**/.terraform.lock.hcl') }}
        restore-keys: |
          ${{ runner.os }}-terraform-plugins-
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
