/* eslint-disable */
// Generated by terraform/scripts/generate_mcp_typescript_client.py from docs/api/mcp-tools-v1.openapi.json.
// Do not edit manually. Regenerate with: make generate-openapi-client

export type JsonObject = Record<string, unknown>;

export interface ToolResponse {
  error?: string;
  result?: Record<string, unknown>;
  success?: boolean;
}

export interface AwscliToolsRunCommandRequest {
  /** Boto3 method name (e.g., 'list_buckets', 'describe_instances') */
  operation?: string;
  /** Dictionary of arguments for the method */
  parameters?: string;
  /** AWS service name (e.g., 's3', 'ec2') */
  service?: string;
}

export interface LocalDevAddMemoryRequest {
  /** Memory content (required) */
  content: string;
  /** Role (user/assistant) */
  role?: string;
}

export interface LocalDevCalculateRequest {
  /** Math expression (required) */
  expression: string;
}

export type LocalDevClearMemoryRequest = Record<string, never>;

export interface LocalDevDeleteValueRequest {
  /** Storage key (required) */
  key: string;
}

export interface LocalDevEchoRequest {
  /** Message to echo back */
  message?: string;
}

export type LocalDevGetEnvRequest = Record<string, never>;

export interface LocalDevGetMemoryRequest {
  /** Maximum entries to return */
  limit?: string;
}

export interface LocalDevGetValueRequest {
  /** Storage key (required) */
  key: string;
}

export interface LocalDevListKeysRequest {
  /** Optional key prefix filter */
  prefix?: string;
}

export interface LocalDevStoreValueRequest {
  /** Storage key (required) */
  key: string;
  /** Value to store */
  value?: string;
}

export interface S3ToolsGetObjectRequest {
  /** Bucket name (required) */
  bucket: string;
  /** Content encoding: text, base64, json */
  encoding?: string;
  /** Object key (required) */
  key: string;
  /** Maximum size to read in bytes */
  max_size?: string;
}

export interface S3ToolsGetObjectMetadataRequest {
  /** Bucket name (required) */
  bucket: string;
  /** Object key (required) */
  key: string;
}

export interface S3ToolsListBucketsRequest {
  /** Optional bucket name prefix filter */
  prefix?: string;
}

export interface S3ToolsListObjectsRequest {
  /** Bucket name (required) */
  bucket: string;
  /** Delimiter for hierarchy */
  delimiter?: string;
  /** Maximum objects to return */
  max_keys?: string;
  /** Object key prefix filter */
  prefix?: string;
}

export interface S3ToolsPutObjectRequest {
  /** Bucket name (required) */
  bucket: string;
  /** Content to upload (required) */
  content: string;
  /** MIME type */
  content_type?: string;
  /** Content encoding: text or base64 */
  encoding?: string;
  /** Object key (required) */
  key: string;
}

export interface TitanicDataFetchDatasetRequest {
  /** List of columns to include */
  columns?: string;
  /** Maximum rows to return */
  limit?: string;
  /** Rows to skip */
  offset?: string;
}

export type TitanicDataGetSchemaRequest = Record<string, never>;

export interface TitanicDataGetStatisticsRequest {
  /** Columns to analyze */
  columns?: string;
}

export interface TitanicDataQueryRequest {
  /** Columns to return */
  columns?: string;
  /** Column:value filter pairs */
  filter?: string;
  /** Maximum rows */
  limit?: string;
}

export interface McpToolRequestOptions extends Omit<RequestInit, 'method' | 'body'> {
  headers?: HeadersInit;
}

export interface McpToolsClientOptions {
  baseUrl?: string;
  fetchFn?: typeof fetch;
  defaultHeaders?: HeadersInit;
}

export const MCP_TOOL_OPERATIONS = {
  'awscli-tools_run_command': { path: "/tools/awscli-tools/run_command", method: 'POST' as const },
  'local-dev_add_memory': { path: "/tools/local-dev/add_memory", method: 'POST' as const },
  'local-dev_calculate': { path: "/tools/local-dev/calculate", method: 'POST' as const },
  'local-dev_clear_memory': { path: "/tools/local-dev/clear_memory", method: 'POST' as const },
  'local-dev_delete_value': { path: "/tools/local-dev/delete_value", method: 'POST' as const },
  'local-dev_echo': { path: "/tools/local-dev/echo", method: 'POST' as const },
  'local-dev_get_env': { path: "/tools/local-dev/get_env", method: 'POST' as const },
  'local-dev_get_memory': { path: "/tools/local-dev/get_memory", method: 'POST' as const },
  'local-dev_get_value': { path: "/tools/local-dev/get_value", method: 'POST' as const },
  'local-dev_list_keys': { path: "/tools/local-dev/list_keys", method: 'POST' as const },
  'local-dev_store_value': { path: "/tools/local-dev/store_value", method: 'POST' as const },
  's3-tools_get_object': { path: "/tools/s3-tools/get_object", method: 'POST' as const },
  's3-tools_get_object_metadata': { path: "/tools/s3-tools/get_object_metadata", method: 'POST' as const },
  's3-tools_list_buckets': { path: "/tools/s3-tools/list_buckets", method: 'POST' as const },
  's3-tools_list_objects': { path: "/tools/s3-tools/list_objects", method: 'POST' as const },
  's3-tools_put_object': { path: "/tools/s3-tools/put_object", method: 'POST' as const },
  'titanic-data_fetch_dataset': { path: "/tools/titanic-data/fetch_dataset", method: 'POST' as const },
  'titanic-data_get_schema': { path: "/tools/titanic-data/get_schema", method: 'POST' as const },
  'titanic-data_get_statistics': { path: "/tools/titanic-data/get_statistics", method: 'POST' as const },
  'titanic-data_query': { path: "/tools/titanic-data/query", method: 'POST' as const },
} as const;

export type McpToolOperationId = keyof typeof MCP_TOOL_OPERATIONS;

export interface McpToolRequestMap {
  "awscli-tools_run_command": AwscliToolsRunCommandRequest;
  "local-dev_add_memory": LocalDevAddMemoryRequest;
  "local-dev_calculate": LocalDevCalculateRequest;
  "local-dev_clear_memory": LocalDevClearMemoryRequest;
  "local-dev_delete_value": LocalDevDeleteValueRequest;
  "local-dev_echo": LocalDevEchoRequest;
  "local-dev_get_env": LocalDevGetEnvRequest;
  "local-dev_get_memory": LocalDevGetMemoryRequest;
  "local-dev_get_value": LocalDevGetValueRequest;
  "local-dev_list_keys": LocalDevListKeysRequest;
  "local-dev_store_value": LocalDevStoreValueRequest;
  "s3-tools_get_object": S3ToolsGetObjectRequest;
  "s3-tools_get_object_metadata": S3ToolsGetObjectMetadataRequest;
  "s3-tools_list_buckets": S3ToolsListBucketsRequest;
  "s3-tools_list_objects": S3ToolsListObjectsRequest;
  "s3-tools_put_object": S3ToolsPutObjectRequest;
  "titanic-data_fetch_dataset": TitanicDataFetchDatasetRequest;
  "titanic-data_get_schema": TitanicDataGetSchemaRequest;
  "titanic-data_get_statistics": TitanicDataGetStatisticsRequest;
  "titanic-data_query": TitanicDataQueryRequest;
}

export interface McpToolResponseMap {
  "awscli-tools_run_command": ToolResponse;
  "local-dev_add_memory": ToolResponse;
  "local-dev_calculate": ToolResponse;
  "local-dev_clear_memory": ToolResponse;
  "local-dev_delete_value": ToolResponse;
  "local-dev_echo": ToolResponse;
  "local-dev_get_env": ToolResponse;
  "local-dev_get_memory": ToolResponse;
  "local-dev_get_value": ToolResponse;
  "local-dev_list_keys": ToolResponse;
  "local-dev_store_value": ToolResponse;
  "s3-tools_get_object": ToolResponse;
  "s3-tools_get_object_metadata": ToolResponse;
  "s3-tools_list_buckets": ToolResponse;
  "s3-tools_list_objects": ToolResponse;
  "s3-tools_put_object": ToolResponse;
  "titanic-data_fetch_dataset": ToolResponse;
  "titanic-data_get_schema": ToolResponse;
  "titanic-data_get_statistics": ToolResponse;
  "titanic-data_query": ToolResponse;
}

export class McpToolsClient {
  private readonly baseUrl: string;
  private readonly fetchFn: typeof fetch;
  private readonly defaultHeaders?: HeadersInit;

  constructor(options: McpToolsClientOptions = {}) {
    this.baseUrl = (options.baseUrl ?? '').replace(/\/$/, '');
    const resolvedFetch = options.fetchFn ?? globalThis.fetch;
    if (typeof resolvedFetch !== 'function') {
      throw new Error('No fetch implementation available. Provide options.fetchFn.');
    }
    this.fetchFn = resolvedFetch.bind(globalThis) as typeof fetch;
    this.defaultHeaders = options.defaultHeaders;
  }

  async invoke<T extends McpToolOperationId>(
    operationId: T,
    payload: McpToolRequestMap[T],
    options: McpToolRequestOptions = {}
  ): Promise<McpToolResponseMap[T]> {
    const meta = MCP_TOOL_OPERATIONS[operationId];
    return this.post(meta.path, payload, options) as Promise<McpToolResponseMap[T]>;
  }

  private async post(path: string, payload: unknown, options: McpToolRequestOptions): Promise<unknown> {
    const headers = new Headers(this.defaultHeaders ?? {});
    headers.set('Content-Type', 'application/json');
    if (options.headers) {
      new Headers(options.headers).forEach((value, key) => headers.set(key, value));
    }

    const response = await this.fetchFn(`${this.baseUrl}${path}`, {
      ...options,
      method: 'POST',
      headers,
      body: JSON.stringify(payload ?? {}),
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`MCP tool request failed (${response.status} ${response.statusText}): ${text}`);
    }

    return response.json();
  }

  /** Run a specific AWS API command */
  async awscliToolsRunCommand(
    payload: AwscliToolsRunCommandRequest,
    options: McpToolRequestOptions = {}
  ): Promise<ToolResponse> {
    return this.invoke("awscli-tools_run_command", payload, options);
  }

  /** Add entry to conversation memory */
  async localDevAddMemory(
    payload: LocalDevAddMemoryRequest,
    options: McpToolRequestOptions = {}
  ): Promise<ToolResponse> {
    return this.invoke("local-dev_add_memory", payload, options);
  }

  /** Perform simple calculations */
  async localDevCalculate(
    payload: LocalDevCalculateRequest,
    options: McpToolRequestOptions = {}
  ): Promise<ToolResponse> {
    return this.invoke("local-dev_calculate", payload, options);
  }

  /** Clear all conversation memory */
  async localDevClearMemory(
    payload: LocalDevClearMemoryRequest,
    options: McpToolRequestOptions = {}
  ): Promise<ToolResponse> {
    return this.invoke("local-dev_clear_memory", payload, options);
  }

  /** Delete a stored value */
  async localDevDeleteValue(
    payload: LocalDevDeleteValueRequest,
    options: McpToolRequestOptions = {}
  ): Promise<ToolResponse> {
    return this.invoke("local-dev_delete_value", payload, options);
  }

  /** Echo back input message */
  async localDevEcho(
    payload: LocalDevEchoRequest,
    options: McpToolRequestOptions = {}
  ): Promise<ToolResponse> {
    return this.invoke("local-dev_echo", payload, options);
  }

  /** Get environment information */
  async localDevGetEnv(
    payload: LocalDevGetEnvRequest,
    options: McpToolRequestOptions = {}
  ): Promise<ToolResponse> {
    return this.invoke("local-dev_get_env", payload, options);
  }

  /** Retrieve conversation memory */
  async localDevGetMemory(
    payload: LocalDevGetMemoryRequest,
    options: McpToolRequestOptions = {}
  ): Promise<ToolResponse> {
    return this.invoke("local-dev_get_memory", payload, options);
  }

  /** Retrieve a stored value */
  async localDevGetValue(
    payload: LocalDevGetValueRequest,
    options: McpToolRequestOptions = {}
  ): Promise<ToolResponse> {
    return this.invoke("local-dev_get_value", payload, options);
  }

  /** List all stored keys */
  async localDevListKeys(
    payload: LocalDevListKeysRequest,
    options: McpToolRequestOptions = {}
  ): Promise<ToolResponse> {
    return this.invoke("local-dev_list_keys", payload, options);
  }

  /** Store a key-value pair */
  async localDevStoreValue(
    payload: LocalDevStoreValueRequest,
    options: McpToolRequestOptions = {}
  ): Promise<ToolResponse> {
    return this.invoke("local-dev_store_value", payload, options);
  }

  /** Get object content from S3 */
  async s3ToolsGetObject(
    payload: S3ToolsGetObjectRequest,
    options: McpToolRequestOptions = {}
  ): Promise<ToolResponse> {
    return this.invoke("s3-tools_get_object", payload, options);
  }

  /** Get object metadata */
  async s3ToolsGetObjectMetadata(
    payload: S3ToolsGetObjectMetadataRequest,
    options: McpToolRequestOptions = {}
  ): Promise<ToolResponse> {
    return this.invoke("s3-tools_get_object_metadata", payload, options);
  }

  /** List S3 buckets */
  async s3ToolsListBuckets(
    payload: S3ToolsListBucketsRequest,
    options: McpToolRequestOptions = {}
  ): Promise<ToolResponse> {
    return this.invoke("s3-tools_list_buckets", payload, options);
  }

  /** List objects in a bucket */
  async s3ToolsListObjects(
    payload: S3ToolsListObjectsRequest,
    options: McpToolRequestOptions = {}
  ): Promise<ToolResponse> {
    return this.invoke("s3-tools_list_objects", payload, options);
  }

  /** Upload content to S3 */
  async s3ToolsPutObject(
    payload: S3ToolsPutObjectRequest,
    options: McpToolRequestOptions = {}
  ): Promise<ToolResponse> {
    return this.invoke("s3-tools_put_object", payload, options);
  }

  /** Fetch Titanic passenger data */
  async titanicDataFetchDataset(
    payload: TitanicDataFetchDatasetRequest,
    options: McpToolRequestOptions = {}
  ): Promise<ToolResponse> {
    return this.invoke("titanic-data_fetch_dataset", payload, options);
  }

  /** Get dataset schema and column information */
  async titanicDataGetSchema(
    payload: TitanicDataGetSchemaRequest,
    options: McpToolRequestOptions = {}
  ): Promise<ToolResponse> {
    return this.invoke("titanic-data_get_schema", payload, options);
  }

  /** Get summary statistics */
  async titanicDataGetStatistics(
    payload: TitanicDataGetStatisticsRequest,
    options: McpToolRequestOptions = {}
  ): Promise<ToolResponse> {
    return this.invoke("titanic-data_get_statistics", payload, options);
  }

  /** Query dataset with filters */
  async titanicDataQuery(
    payload: TitanicDataQueryRequest,
    options: McpToolRequestOptions = {}
  ): Promise<ToolResponse> {
    return this.invoke("titanic-data_query", payload, options);
  }

}
